// Code generated by neuron/generator. DO NOT EDIT.
// This file was generated at:
// Fri, 17 Jul 2020 12:54:46 +0200

package filters

import (
	"strconv"

	"github.com/neuronlabs/neuron/errors"
	"github.com/neuronlabs/neuron/mapping"
)

// Compile time check if QueryModel implements mapping.Model interface.
var _ mapping.Model = &QueryModel{}

// NeuronCollectionName implements mapping.Model interface method.
// Returns the name of the collection for the 'QueryModel'.
func (q *QueryModel) NeuronCollectionName() string {
	return "query_models"
}

// IsPrimaryKeyZero implements mapping.Model interface method.
func (q *QueryModel) IsPrimaryKeyZero() bool {
	return q.ID == 0
}

// GetPrimaryKeyValue implements mapping.Model interface method.
func (q *QueryModel) GetPrimaryKeyValue() interface{} {
	return q.ID
}

// GetPrimaryKeyStringValue implements mapping.Model interface method.
func (q *QueryModel) GetPrimaryKeyStringValue() (string, error) {
	return strconv.FormatInt(int64(q.ID), 10), nil
}

// GetPrimaryKeyAddress implements mapping.Model interface method.
func (q *QueryModel) GetPrimaryKeyAddress() interface{} {
	return &q.ID
}

// GetPrimaryKeyHashableValue implements mapping.Model interface method.
func (q *QueryModel) GetPrimaryKeyHashableValue() interface{} {
	return q.ID
}

// GetPrimaryKeyZeroValue implements mapping.Model interface method.
func (q *QueryModel) GetPrimaryKeyZeroValue() interface{} {
	return 0
}

// SetPrimaryKey implements mapping.Model interface method.
func (q *QueryModel) SetPrimaryKeyValue(value interface{}) error {
	if v, ok := value.(int); ok {
		q.ID = v
		return nil
	}
	// Check alternate types for given field.
	switch valueType := value.(type) {
	case int8:
		q.ID = int(valueType)
	case int16:
		q.ID = int(valueType)
	case int32:
		q.ID = int(valueType)
	case int64:
		q.ID = int(valueType)
	case uint:
		q.ID = int(valueType)
	case uint8:
		q.ID = int(valueType)
	case uint16:
		q.ID = int(valueType)
	case uint32:
		q.ID = int(valueType)
	case uint64:
		q.ID = int(valueType)
	case float32:
		q.ID = int(valueType)
	case float64:
		q.ID = int(valueType)
	default:
		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid value: '%T' for the primary field for model: 'QueryModel'", value)
	}
	return nil
}

// SetPrimaryKeyStringValue implements mapping.Model interface method.
func (q *QueryModel) SetPrimaryKeyStringValue(value string) error {
	tmp, err := strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	if err != nil {
		return err
	}
	q.ID = int(tmp)
	return nil
}

// Compile time check if QueryModel implements mapping.Fielder interface.
var _ mapping.Fielder = &QueryModel{}

// GetFieldsAddress gets the address of provided 'field'.
func (q *QueryModel) GetFieldsAddress(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return &q.ID, nil
	case 1: // StringAttr
		return &q.StringAttr, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: QueryModel'", field.Name())
}

// GetFieldZeroValue implements mapping.Fielder interface.s
func (q *QueryModel) GetFieldZeroValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return 0, nil
	case 1: // StringAttr
		return "", nil
	default:
		return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
	}
}

// IsFieldZero implements mapping.Fielder interface.
func (q *QueryModel) IsFieldZero(field *mapping.StructField) (bool, error) {
	switch field.Index[0] {
	case 0: // ID
		return q.ID == 0, nil
	case 1: // StringAttr
		return q.StringAttr == "", nil
	}
	return false, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
}

// SetFieldZeroValue implements mapping.Fielder interface.s
func (q *QueryModel) SetFieldZeroValue(field *mapping.StructField) error {
	switch field.Index[0] {
	case 0: // ID
		q.ID = 0
	case 1: // StringAttr
		q.StringAttr = ""
	default:
		return errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
	}
	return nil
}

// GetHashableFieldValue implements mapping.Fielder interface.
func (q *QueryModel) GetHashableFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return q.ID, nil
	case 1: // StringAttr
		return q.StringAttr, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: 'QueryModel'", field.Name())
}

// GetFieldValue implements mapping.Fielder interface.
func (q *QueryModel) GetFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return q.ID, nil
	case 1: // StringAttr
		return q.StringAttr, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: QueryModel'", field.Name())
}

// SetFieldValue implements mapping.Fielder interface.
func (q *QueryModel) SetFieldValue(field *mapping.StructField, value interface{}) (err error) {
	switch field.Index[0] {
	case 0: // ID
		if v, ok := value.(int); ok {
			q.ID = v
			return nil
		}

		switch v := value.(type) {
		case int8:
			q.ID = int(v)
		case int16:
			q.ID = int(v)
		case int32:
			q.ID = int(v)
		case int64:
			q.ID = int(v)
		case uint:
			q.ID = int(v)
		case uint8:
			q.ID = int(v)
		case uint16:
			q.ID = int(v)
		case uint32:
			q.ID = int(v)
		case uint64:
			q.ID = int(v)
		case float32:
			q.ID = int(v)
		case float64:
			q.ID = int(v)
		default:
			return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
		}
		return nil
	case 1: // StringAttr
		if v, ok := value.(string); ok {
			q.StringAttr = v
			return nil
		}

		// Check alternate types for the StringAttr.
		if v, ok := value.([]byte); ok {
			q.StringAttr = string(v)
			return nil
		}
		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
	default:
		return errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for the model: 'QueryModel'", field.Name())
	}
}

// SetPrimaryKeyStringValue implements mapping.Model interface method.
func (q *QueryModel) ParseFieldsStringValue(field *mapping.StructField, value string) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	case 1: // StringAttr
		return value, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: QueryModel'", field.Name())
}
